-- Os dados de teste são criados pelo DataInitializer.java nesta branch.
-- O hash do usuário de teste depende do PasswordEncoder ativo (Argon2+Pepper)
-- e não pode ser computado de forma estática em SQL.
